sanemat/do-not-merge-wip-for-github

- package.json
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build5967216560216092362">David Update as a Service - Tachikoma.io</a>
> Exec tachikoma update 20150131090928

- package.json
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build5969753308551884167">David Update as a Service - Tachikoma.io</a>
> Exec tachikoma update 20150207090832

- LICENSE.txt
- README.md
- package.json
> chore(app): add MIT license

- package.json
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6020869789593271055">David Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6020869789593271055">2015-06-28 Updated permissions - Tachikoma.io</a>
> Exec tachikoma update 20150628102715

- package.json
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6028479928362474081">David Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6028479928362474081">2015-06-28 Updated permissions - Tachikoma.io</a>
> Exec tachikoma update 20150719102720

- package.json
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6048773619228381148">David Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6048773619228381148">2015-06-28 Updated permissions - Tachikoma.io</a>
> Exec tachikoma update 20150913102718

- package.json
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6061457226214836067">David Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6061457226214836067">2015-06-28 Updated permissions - Tachikoma.io</a>
> Exec tachikoma update 20151018102739

- package.json
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6063993936899010413">David Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6063993936899010413">2015-06-28 Updated permissions - Tachikoma.io</a>
> Exec tachikoma update 20151025102712

- package.json
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6066530653980680074">David Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6066530653980680074">2015-06-28 Updated permissions - Tachikoma.io</a>
> Exec tachikoma update 20151101102714

- package.json
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6096971235193880028">David Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6096971235193880028">2015-06-28 Updated permissions - Tachikoma.io</a>
> Exec tachikoma update 20160124102733

- package.json
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6099507955311012483">David Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6099507955311012483">2015-06-28 Updated permissions - Tachikoma.io</a>
> Exec tachikoma update 20160131102741

- README.md
> docs(readme): add version badge

- app/scripts/contentscript.js
`.js-merge-branch-action` is not used now.
And... web font is not used.
> Fix a detect to merge button

- app/scripts/contentscript.js
Examples
wip: at the start of the line
anywhere (wip)
anywhere [wip]
> Add support for () and :

- app/scripts/contentscript.js
Hi @sanemat,
It would be superb if it handles `[DONT MERGE]` and `[DON'T MERGE]` as well.
> Improve title regex

- bin/prepare.js
- bin/update-manifest.js
- package-lock.json
- package.json
- webextension/_locales/en/messages.json
- webextension/manifest.json
- prepare
- build
- manifest
- package
> prepare, build and package

- webextension/manifest.json
- webextension/options.html
- webpack.config.js
- options.html
- options.js
- adjust script names
> options page

- package-lock.json
- package.json
- src/background.js
> chore(deps): add webextension-polyfill

- src/background.js
- src/content_script.js
Use `browser.storage`
This does not care about migration from `window.localStorage` yet.
> Use storage

- resource-for-webstore.md
> docs(resource): update

- .travis.yml
> chore(deps): bump ruby to 2.6.5

- .travis.yml
> chore(deps): bump node to latest

- LICENSE.txt
- README.md
> chore(license): remove end year

- .travis.yml
- Gruntfile.js
- package-lock.json
- package.json
> Remove compass

- Gruntfile.js
- package-lock.json
- package.json
> Remove coffee

- app/scripts/contentscript.js
> chore(content): issue title

- app/scripts/contentscript.js
> chore(content): button merge

- app/scripts/contentscript.js
> chore(content): button merge option

- app/scripts/contentscript.js
> chore(content): fix typo

- app/scripts/contentscript.js
> Remove icon html and $buttonMerge

- app/scripts/contentscript.js
> fix(textcontent): detect commit message

- app/options.html
- app/scripts/contentscript.js
- app/scripts/options.js
> Drop branch protection

- app/scripts/contentscript.js
> fix(content): detect issue label

- app/scripts/contentscript.js
use strict into anonymous block
> chore(content): use strict into anonymous block

- app/scripts/contentscript.js
refactor wip task list
related to #236
> refactor wip task list

- .bowerrc
- Gruntfile.js
- app/manifest.json
- bower.json
- package-lock.json
- package.json
> Remove jQuery and bower

- .dependabot/config.yml
> chore(deps): dependabot

- package-lock.json
> chore(deps): re-create package lock

- package-lock.json
> chore(deps): update lockfileVersion from 1 to 2

- .github/workflows/build.yml
use github actions
close #226
fixes #326
> chore(build): use github actions

- README.md
> docs(readme): drop travis-ci, david status

- .tachikoma.yml
> chore(tools): drop tachikoma settings

- resource-for-webstore.md
> docs(resource): developer dashboard

- resource-for-webstore.md
> docs(resource): release operation

- package-lock.json
- package.json
v4 doesn't work wtih current settings.
> chore(dev-deps): downgrade cc-ci to v3

- app/manifest.json
> fix(permission): drop activetab
